# Generated by Django 5.1.6 on 2025-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='type_paiement',
            field=models.CharField(choices=[('jour', 'Par jour'), ('semaine', 'Par semaine'), ('mois', 'Par mois')], default='mois', max_length=10),
        ),
    ]
