# Generated by Django 5.1.6 on 2025-10-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_discussion_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contenue',
            new_name='contenu',
        ),
    ]
