# Generated by Django 5.1.6 on 2025-10-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='nom',
            new_name='titre',
        ),
    ]
