# Generated by Django 5.1.6 on 2025-10-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_nom_produit_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='titre',
            new_name='nom',
        ),
    ]
