# Generated by Django 5.1.6 on 2025-10-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_avissite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvisSite',
        ),
    ]
