# Generated by Django 5.1.6 on 2025-10-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_avis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
