# Generated by Django 5.1.6 on 2025-10-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_favoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
    ]
