# Generated by Django 5.1.6 on 2025-10-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_favoris_favoris'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
