# Generated by Django 5.1.6 on 2025-10-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_favoris'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
