# Generated by Django 5.1.6 on 2025-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='competence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='description',
            field=models.TextField(),
        ),
    ]
