# Generated by Django 5.1.6 on 2025-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_cv_competence_alter_cv_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offres/images/'),
        ),
    ]
