# Generated by Django 5.1.6 on 2025-10-21 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cv_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
