# Generated by Django 5.1.6 on 2025-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_cv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
