# Generated by Django 5.1.6 on 2025-10-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_boost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='suivre',
        ),
    ]
