# Generated by Django 5.1.6 on 2025-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_suivi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
