# Generated by Django 5.1.6 on 2025-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_cv_age_cv_pays_offre_likes_alter_cv_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
