from django.urls import path
from . import views
from pro.settings import MEDIA_ROOT,MEDIA_URL,MIDDLEWARE
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index , name='index'),
    path('inscription/',views.inscription, name='inscription'),
    path('connexion/',views.connexion , name='connexion'),
    path('deconnexion/',views.deconnexion , name='deconnexion'),
    path('produit/',views.produit , name='produit'),
    path('creation_produit/',views.creation_produit , name='creation_produit'),
    path('discussion/<int:user_id>/',views.discussion, name='discussion'),
    path('user_list/',views.user_list, name='user_list'),
    path('accueil/',views.accueil , name='accueil'),
    path('creation_offre/',views.creation_offre , name='creation_offre'),
    path('supprimer_offre/<int:id>/',views.supprimer_offre, name='supprimer_offre'),
    path('detail_offre/<int:id>/',views.detail_offre, name='detail_offre'),
    # path('detail_produit/<int:id>/',views.detail_produit, name='detail_produit'),
    path('detail_cv/<int:id>/',views.detail_cv, name='detail_cv'),
    path('supprimer_cv/<int:id>/',views.supprimer_cv, name='supprimer_cv'),
    path('supprimer_publication/<int:id>/',views.supprimer_publication, name='supprimer_publication'),
    # path('supprimer_produit/<int:id>/',views.supprimer_produit, name='supprimer_produit'),
    path('profil/', views.profil_view, name='profil'),
    path('cv/', views.cv, name='cv'),
    path('publication/', views.publication, name='publication'),
    path('creation_publication/', views.creation_publication, name='creation_publication'),
    # path('chat_gpt/', views.chat_gpt, name='chat_gpt'),
    path('creation_cv/', views.creation_cv, name='creation_cv'),
    path('modif_offre/<int:id>', views.modif_offre, name='modif_offre'),
    path('modif_cv/<int:id>', views.modif_cv, name='modifier_cv'),
    path('modifier_publication/<int:id>', views.modifier_publication, name='modifier_publication'),
    path('notification/',views.Notification_view,name='notification'),
    path('notif_all/',views.notif_all,name='notif_all'),
    path('add_page/',views.add_page,name='add_page'),
    path('boost_page/',views.boost_page,name='boost_page'),
    path('suivre/<int:id>',views.suivre,name='suivre'),
     path('options_avance/',views.options_avance,name='options_avance'),
     path('profil/',views.total_like_offre,name='total_like_offre'),
     path('accueil/<int:offre_id>/like',views.like_offre,name='like_offre'),
     path('publication/<int:publication_id>/like',views.like_publication,name='like_publication'),
     path('publication/<int:id>/commentaires/', views.commentaires_view, name='commentaires'),
     path('chat/', views.chat_with_lia, name='chat'),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)